### ISSUE TITLE
POSIX.1-2017 compliant identifiers

### ISSUE THREAD

**Issue by MoritzMaxeiner** [JuliaStrings/utf8proc#168]
I don't know if POSIX compliance (Linux,BSD,...) is of import to you, but if it is you need to be aware that your identifiers ending with `_t`  are non-compliant, as per [1].

[1] https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_02_02

**Comment by stevengj** [comment]
I'm not sure it is worth changing it (which would break backward compatibility), since the odds of a future POSIX standard giving a conflicting definition of `utfproc_*_t` are negligible — the only practical benefit is eliminating warnings that might be emitted(?) I guess.

(The code currently compiles without warning on Linux and BSD with `-Wall -pedantic`, so even the possibility of warnings seems theoretical?  Is there a compiler option where it actually complains?)

**Comment by MoritzMaxeiner** [comment]
>  the odds of a future POSIX standard giving a conflicting definition of utfproc_*_t are negligible

I agree; it's just something to be aware of so it's a choice, not an oversight.

> the only practical benefit would be eliminating warnings that might be emitted
>  Is there a compiler option where it actually complains?

I know of no compiler that warns about this, so the only practical benefit would be the ability to claim/guarantee that utf8proc works on all POSIX compliant systems without having to spend time testing/verifying it (a system utf8proc doesn't work on wouldn't be POSIX compliant by definition, then).

Anyway, just close this as a WONTFIX, then, as it's an intentional design choice.
