### ISSUE TITLE
Should U+22A5 and U+27C2 be equivalent?

### ISSUE THREAD

**Issue by jonas-schulze** [JuliaStrings/utf8proc#218]
This is a follow up to https://github.com/JuliaLang/julia/issues/39350#issuecomment-767777438.

In Julia U+22A5 (`⊥` or `\bot`) and U+27C2 (`⟂` or `\perp`) are different, even under normalization. Is this intended behavior or should they be equivalent?

cc: @mcabbott, @StefanKarpinski

**Comment by StefanKarpinski** [comment]
The Unicode Consortium decides on normalization rules, this repo just implements them. That said, Julia does some additional normalization, IIRC.

**Comment by stevengj** [comment]
Yes, they aren't equivalent according to Unicode, so this is not a utf8proc issue.

See also the discussion in #11: we do provide the hooks for custom normalizations, and Julia takes advantage of this (JuliaLang/julia#19464).   So, we could add it as a new Julia-specific normalization, but we've been conservative about this — basically, we've used it for confusable characters which show up frequently because they have popular input methods.
