### ISSUE TITLE
how to cmake c++ library?

### ISSUE THREAD

**Issue by liumingzhu6060** [JuliaStrings/utf8proc#264]
May I ask how to compile C++libraries, I want to use it in visual studio

**Comment by stevengj** [comment]
A C library like this can be called as-is by C++ code.  In fact, the `utfproc.h` header file already has [C++ `extern "C"` boilerplate](https://github.com/JuliaStrings/utf8proc/blob/dce38103bed462c4f87bfcdb80172ec22312e595/utf8proc.h#L139-L141) so that a C++ compiler will correctly call the code.

(Note that you have to link the library, not just `#include` the header.)

**Comment by stevengj** [comment]
(We should ideally fix `utf8proc.c`so that it can compile directly in a C++ compiler, though; currently C++ complains about some C-isms like missing prototypes.)
